export declare const formatDate: (date: Date | string, formatStr?: string) => string;
export declare const formatTime: (date: Date | string) => string;
export declare const formatDateTime: (date: Date | string) => string;
export declare const getRelativeTime: (date: Date | string) => string;
export declare const isDatePast: (date: Date | string) => boolean;
export declare const isDateFuture: (date: Date | string) => boolean;
export declare const isDateAfter: (date1: Date | string, date2: Date | string) => boolean;
export declare const isDateBefore: (date1: Date | string, date2: Date | string) => boolean;
export declare const addDaysToDate: (date: Date | string, days: number) => Date;
export declare const addMinutesToDate: (date: Date | string, minutes: number) => Date;
export declare const addHoursToDate: (date: Date | string, hours: number) => Date;
export declare const getMinutesDifference: (date1: Date | string, date2: Date | string) => number;
export declare const getHoursDifference: (date1: Date | string, date2: Date | string) => number;
export declare const getStartOfDay: (date: Date | string) => Date;
export declare const getEndOfDay: (date: Date | string) => Date;
export declare const canCancelBooking: (classStartTime: Date | string, hoursBeforeClass?: number) => boolean;
export declare const getMinutesRemaining: (expiryDate: Date | string) => number;
//# sourceMappingURL=dates.d.ts.map