export declare const formatName: (name: string) => string;
export declare const getInitials: (firstName: string, lastName: string) => string;
export declare const formatPhone: (phone: string) => string;
export declare const truncate: (text: string, maxLength: number) => string;
export declare const generateRandomString: (length: number) => string;
export declare const pluralize: (count: number, singular: string, plural: string) => string;
export declare const formatCapacity: (current: number, max: number) => string;
export declare const getCapacityPercentage: (current: number, max: number) => number;
export declare const formatDifficulty: (level: string) => string;
export declare const formatStatus: (status: string) => string;
//# sourceMappingURL=formatters.d.ts.map